#!/bin/bash 
SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`

if [ ${PWD} != $SCRIPTPATH  ]; then
        echo "run from the script dir (${SCRIPTPATH})"
        exit 1
fi 

cd $SCRIPTPATH/..

SCRIPTPATHPARENT=$PWD
shift $@
echo "Starting SparqlMap...." >&2
#textdb.allow_full_path=false allows access to the full file system, see:  http://www.hsqldb.org/doc/guide/texttables-chapt.html
java  -classpath "lib/sparqlmap/*:lib-jdbc/*" -Dtextdb.allow_full_path=false sparqlmap  $@